#!/bin/bash

#PBS -N ...imh
#PBS -joe
#PBS -o OUT
#PBS -q teaching
#PBS -l epilogue=~ggdagw/epilogue.sh
#PBS -l nodes=1:ppn=16,walltime=00:00:30

#! Mail to user if job aborts
#PBS -m a

#! application name
#application="ddt -offline report.html ./d2q9-bgk.exe"
#application="./cachegrind.sh"
application="./d2q9-bgk.exe"

#! Run options for the application
options="input_256x256.params obstacles_256x256.dat"

###############################################################
### You should not have to change anything below this line ####
###############################################################

#! change the working directory (default is home directory)

cd $PBS_O_WORKDIR

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo PBS job ID is $PBS_JOBID
echo This jobs runs on the following machines:
echo `cat $PBS_NODEFILE | uniq`

numnodes=`wc $PBS_NODEFILE | awk '{ print $1 }'`

export OMP_NUM_THREADS=$numnodes

#! Run the executable
$application $options
#amplxe-cl -quiet -collect hotspots -result-dir r001hs $application $options
