#!/bin/bash

#PBS -N STDIN
#PBS -joe
#PBS -o d2q9-bgk.out
#PBS -q teaching
#PBS -l epilogue=~ggdagw/epilogue.sh
#PBS -l nodes=4:ppn=16,walltime=00:00:60

#! Mail to user if job aborts
#PBS -m a

#! application name
application="./d2q9-bgk"

#! Run options for the application
options="input_256x256.params obstacles_256x256.dat"

###############################################################
### You should not have to change anything below this line ####
###############################################################

#! change the working directory (default is home directory)

cd $PBS_O_WORKDIR

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo PBS job ID is $PBS_JOBID
echo This jobs runs on the following machines:
echo `cat $PBS_NODEFILE | uniq`

#! Create a machine file for MPI
cat $PBS_NODEFILE > machine.file.$PBS_JOBID

numnodes=`wc $PBS_NODEFILE | awk '{ print $1 }'`

#! Run the parallel MPI executable (nodes*ppn)
mpirun -np $numnodes -machinefile machine.file.$PBS_JOBID $application $options
#mpirun -report-bindings -np $numnodes -machinefile machine.file.$PBS_JOBID $application $options 
#mpirun -report-bindings -np $numnodes -machinefile machine.file.$PBS_JOBID $application $options 
#mpirun -report-bindings -np $numnodes -machinefile machine.file.$PBS_JOBID $application $options 

#export OMP_NUM_THREADS=$numnodes

#! Run the executable
#$application $options
